import unittest
import json
from pathlib import Path

from src.guard_differential import jsonl
from src.requirement_projection import CARD_OUTPUT, ROOT

from src.requirement_projection import card_evidence_status, occurrence_identity, pair_evidence_status


class RequirementProjectionHelpersTest(unittest.TestCase):
    def test_pair_source_partition_is_descriptive_and_not_a_truth_label(self):
        self.assertEqual(pair_evidence_status({"forge"}), "FORGE_ONLY")
        self.assertEqual(pair_evidence_status({"xmage"}), "XMAGE_ONLY")
        self.assertEqual(pair_evidence_status({"forge", "xmage"}), "MULTI_SOURCE_EVIDENCE")
        self.assertEqual(pair_evidence_status(set()), "NO_EVIDENCE")

    def test_card_projection_marks_partial_or_unresolved_without_capability_claim(self):
        self.assertEqual(card_evidence_status([], False), "NO_EVIDENCE")
        self.assertEqual(card_evidence_status([], True), "UNRESOLVED")
        self.assertEqual(card_evidence_status([{"forge"}], True), "PARTIAL_REQUIREMENT_EVIDENCE")
        self.assertEqual(card_evidence_status([{"forge"}], False), "SINGLE_SOURCE_EVIDENCE")
        self.assertEqual(card_evidence_status([{"forge", "xmage"}], False), "MULTI_SOURCE_EVIDENCE")

    def test_occurrence_identity_binds_oracle_source_record_construct_and_ordinal(self):
        first=occurrence_identity("oid","forge","forge@rev:row:1","ChangeZone","zone_transition",0)
        repeat=occurrence_identity("oid","forge","forge@rev:row:1","ChangeZone","zone_transition",0)
        second=occurrence_identity("oid","forge","forge@rev:row:1","ChangeZone","zone_transition",1)
        self.assertEqual(first,repeat)
        self.assertNotEqual(first["id"],second["id"])
        self.assertEqual(first["components"]["oracle_id"],"oid")

    def test_generated_projection_reconciles_counts_and_excludes_removed_occurrences(self):
        diff_path=ROOT/"extractor_0_2_0_to_0_2_1_diff.json"
        manifest_path=ROOT/"requirement_evidence_projection_manifest.yaml"
        profile_path=ROOT/"requirement_evidence_projection.yaml"
        if not (CARD_OUTPUT.exists() and diff_path.exists() and manifest_path.exists() and profile_path.exists()):
            self.skipTest("Full pinned projection artifacts are generated by the Phase 0.2D pipeline")
        diff=json.loads(diff_path.read_text(encoding="utf-8"))
        removed={(str(r["oracle_id"]),r["source"],r["source_record_identity"],r["external_construct"],r["requirement"],int(r["occurrence_index"])) for r in diff["removed_occurrences"]}
        seen=set();pairs=0;occurrences=0;warnings=0;oracle_ids=set()
        for card in jsonl(CARD_OUTPUT):
            self.assertNotIn(card["oracle_id"],oracle_ids)
            oracle_ids.add(card["oracle_id"]);warnings+=len(card["summary"]["source_warnings"])
            for requirement in card["requirements"]:
                pairs+=1
                self.assertIsNone(requirement["requirement_precision"])
                for path in requirement["evidence_paths"]:
                    for occurrence in path["occurrences"]:
                        components=occurrence["occurrence_identity"]["components"]
                        key=(components["oracle_id"],components["source"],components["source_record_identity"],components["external_construct"],components["requirement_id"],components["occurrence_index"])
                        self.assertNotIn(key,removed)
                        self.assertNotIn(occurrence["occurrence_identity"]["id"],seen)
                        seen.add(occurrence["occurrence_identity"]["id"]);occurrences+=1
        self.assertEqual(len(oracle_ids),36923)
        self.assertEqual(pairs,21196)
        self.assertEqual(occurrences,29182)
        self.assertEqual(warnings,9)


if __name__=="__main__":
    unittest.main()
